services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata6_data:/var/lib/dbdata6/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo

  redis:
    image: redis:7.2.3
    restart: always
    ports:
      - 6379:6379

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: myminio
  	  MINIO_ROOT_PASSWORD: password@123D
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: unless-stopped

  wpcas-survey-ui:
    image: ghcr.io/compass/wpcas-survey-ui:0.1.3
    restart: always
    ports:
      - 3300:3000

  wpcas_service:
    image: ghcr.io/compass/wpcas-service:0.1.10
    restart: always
    ports:
      - 4010:4010
    depends_on:
      - postgres

  wallet:
    image: ghcr.io/compass/wallet-service:0.1.5
    restart: always
    ports:
    - 4022:4022
    depends_on:
      - postgres

  marketplace-ui:
    image: ghcr.io/compass/marketplace-ui:0.1.7
    restart: always
    ports:
      - "3400:3000"

  marketplace_portal:
    image: ghcr.io/compass/marketplace-portal:0.2.4
    restart: always
    ports:
      - "4020:4020"
    depends_on:
      - postgres

  bap_service:
    image: ghcr.io/compass/bap:0.1.2
    restart: always
    ports:
    - "4021:4021"
    depends_on:
      - redis

  course_manager:
    image: ghcr.io/compass/course-manager:0.2.1
    restart: always
    ports:
      - "4030:4030"
    depends_on:
      - postgres

  course-manager-ui:
    image: ghcr.io/compass/3cp-ui:0.1.4
    restart: always
    ports:
      - "3500:3000"

  admin-ui:
    image: ghcr.io/compass/admin-ui:0.1.4
    restart: always
    ports:
      - "3200:3000"
 
  passbook:
    restart: always
    image: ghcr.io/compass/passbook:0.1.5
    ports:
      - "3000:3000"

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - "3060:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
      MB_DB_DBNAME: postgres
    depends_on:
      - postgres
